name = "AVTM SMP - Vanilla+"
author = "kcesar.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50537905b5791c0308bf5c5cd81d2838debef4dc9bb201d33db595ab2edf795a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
