name = "AVTM SMP - Vanilla+"
author = "kcesar.dev"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e4c91bb8100a8a5572d2afcaa5c3235c85c93371ef75d721c7101b1930274ae"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
