name = "AVTM SMP - Vanilla+"
author = "kcesar.dev"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee00e3e685212238f4c6f90eda4d312fd9ee033d7e87989be80533cb2af1054f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
