name = "AVTM SMP - Vanilla+"
author = "kcesar.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7114c602f760895bd919a168e69fff6e7cf544c122995c1ee005f1ef34ab1a27"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
