name = "AVTM SMP - Vanilla+"
author = "kcesar.dev"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "524d3af166866cebec639c5f706bfe34b805c35d686d27e4d01f08a5aa05c56f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
