name = "AVTM SMP - Vanilla+"
author = "kcesar.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c9e39216185846e24cd0634300357982fea42aaaf480f7dc6acb100ab6bba91"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
